version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: sudo apt install npm
      - run: npm install mocha --save-dev
      - run: mkdir ~/junit
      - run:
          command: mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit          
